# Project: WordCount
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = WordCount/main.o
LINKOBJ  = WordCount/main.o
LIBS     = -L"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/lib" -L"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/include" -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/include" -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/王睿/Desktop/Develp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WordCount.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

WordCount/main.o: WordCount/main.cpp
	$(CPP) -c WordCount/main.cpp -o WordCount/main.o $(CXXFLAGS)
